"use client";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface DownloadSummaryButtonProps {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}

export function DownloadSummaryButton({title,summaryText,fileName,createdAt}: DownloadSummaryButtonProps) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by SummariseIt
`;
    const blob = new Blob([summaryContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button size="sm" className="h-8 px-3 bg-white text-black/80 hover:bg-gray-100" onClick={handleDownload}>
      <Download className="h-4 w-4 mr-1" />
      <p>Download Summary</p>
    </Button>
  );
}
